mkdir -p _sources/Unit-0-Preamble
git mv _sources/Unit1-Getting-Started/topic-1-1-getting-started.rst _sources/Unit-0-Preamble/topic-1-1-getting-started.rst
git mv _sources/Unit1-Getting-Started/preface.rst _sources/Unit-0-Preamble/preface.rst
git mv _sources/Unit1-Getting-Started/aboutcsa.rst _sources/Unit-0-Preamble/aboutcsa.rst
git mv _sources/Unit1-Getting-Started/csptransition.rst _sources/Unit-0-Preamble/csptransition.rst
git mv _sources/Unit1-Getting-Started/javaIDEs.rst _sources/Unit-0-Preamble/javaIDEs.rst
git mv _sources/Unit1-Getting-Started/growthMindset.rst _sources/Unit-0-Preamble/growthMindset.rst
git mv _sources/Unit1-Getting-Started/ptest1.rst _sources/Unit-0-Preamble/ptest1.rst
git mv _sources/Unit1-Getting-Started/survey.rst _sources/Unit-0-Preamble/survey.rst
git mv _sources/Unit1-Getting-Started/topic-1-2-java-intro.rst _sources/Unit-0-Preamble/topic-1-2-java-intro.rst
mkdir -p _sources/Unit-1-Expressions
git mv _sources/Unit3-If-Statements/topic-3-1-booleans.rst _sources/Unit-1-Expressions/topic-3-1-booleans.rst
git mv _sources/Unit1-Getting-Started/topic-1-6-casting.rst _sources/Unit-1-Expressions/topic-1-6-casting.rst
git mv _sources/Unit1-Getting-Started/topic-1-7-summary.rst _sources/Unit-1-Expressions/topic-1-7-summary.rst
git mv _sources/Unit1-Getting-Started/topic-1-8-practice-mixed-code.rst _sources/Unit-1-Expressions/topic-1-8-practice-mixed-code.rst
git mv _sources/Unit1-Getting-Started/topic-1-8-practice-mixed-code-toggle.rst _sources/Unit-1-Expressions/topic-1-8-practice-mixed-code-toggle.rst
git mv _sources/Unit1-Getting-Started/topic-1-9-practice-coding.rst _sources/Unit-1-Expressions/topic-1-9-practice-coding.rst
git mv _sources/Unit1-Getting-Started/Exercises.rst _sources/Unit-1-Expressions/Exercises.rst
mkdir -p _sources/Unit-2-Variables-and-assignment
git mv _sources/Unit1-Getting-Started/topic-1-3-variables.rst _sources/Unit-2-Variables-and-assignment/topic-1-3-variables.rst
git mv _sources/Unit1-Getting-Started/topic-1-4-assignment.rst _sources/Unit-2-Variables-and-assignment/topic-1-4-assignment.rst
git mv _sources/Unit1-Getting-Started/topic-1-5-shortcutoperators.rst _sources/Unit-2-Variables-and-assignment/topic-1-5-shortcutoperators.rst
mkdir -p _sources/Unit-3-Arrays
git mv _sources/Unit6-Arrays/topic-6-1-array-basics.rst _sources/Unit-3-Arrays/topic-6-1-array-basics.rst
git mv _sources/Unit6-Arrays/topic-6-2-traversing-arrays.rst _sources/Unit-3-Arrays/topic-6-2-traversing-arrays.rst
git mv _sources/Unit6-Arrays/topic-6-3-arrays-with-foreach.rst _sources/Unit-3-Arrays/topic-6-3-arrays-with-foreach.rst
git mv _sources/Unit6-Arrays/topic-6-4-array-algorithms.rst _sources/Unit-3-Arrays/topic-6-4-array-algorithms.rst
git mv _sources/Unit6-Arrays/horseBarnA.rst _sources/Unit-3-Arrays/horseBarnA.rst
git mv _sources/Unit6-Arrays/horseBarnB.rst _sources/Unit-3-Arrays/horseBarnB.rst
git mv _sources/Unit6-Arrays/selfDivisorB.rst _sources/Unit-3-Arrays/selfDivisorB.rst
git mv _sources/Unit6-Arrays/soundA.rst _sources/Unit-3-Arrays/soundA.rst
git mv _sources/Unit6-Arrays/soundB.rst _sources/Unit-3-Arrays/soundB.rst
git mv _sources/Unit6-Arrays/numberCubeA.rst _sources/Unit-3-Arrays/numberCubeA.rst
git mv _sources/Unit6-Arrays/numberCubeB.rst _sources/Unit-3-Arrays/numberCubeB.rst
git mv _sources/Unit6-Arrays/topic-6-5-summary.rst _sources/Unit-3-Arrays/topic-6-5-summary.rst
git mv _sources/Unit6-Arrays/ArrayParsonsPractice.rst _sources/Unit-3-Arrays/ArrayParsonsPractice.rst
git mv _sources/Unit6-Arrays/Arrays-mixed-code-toggle.rst _sources/Unit-3-Arrays/Arrays-mixed-code-toggle.rst
git mv _sources/Unit6-Arrays/ArrayPractice.rst _sources/Unit-3-Arrays/ArrayPractice.rst
git mv _sources/Unit6-Arrays/Exercises.rst _sources/Unit-3-Arrays/ArrayExercises.rst
git mv _sources/Unit6-Arrays/arrayExam.rst _sources/Unit-3-Arrays/arrayExam.rst
git mv _sources/Unit8-2DArray/topic-8-1-2D-arrays.rst _sources/Unit-3-Arrays/topic-8-1-2D-arrays.rst
git mv _sources/Unit8-2DArray/topic-8-1-2D-arrays-Day1.rst _sources/Unit-3-Arrays/topic-8-1-2D-arrays-Day1.rst
git mv _sources/Unit8-2DArray/topic-8-1-2D-arrays-Day2.rst _sources/Unit-3-Arrays/topic-8-1-2D-arrays-Day2.rst
git mv _sources/Unit8-2DArray/topic-8-2-2D-array-loops.rst _sources/Unit-3-Arrays/topic-8-2-2D-array-loops.rst
git mv _sources/Unit8-2DArray/topic-8-2-2D-array-loops-Day1.rst _sources/Unit-3-Arrays/topic-8-2-2D-array-loops-Day1.rst
git mv _sources/Unit8-2DArray/topic-8-2-2D-array-loops-Day2.rst _sources/Unit-3-Arrays/topic-8-2-2D-array-loops-Day2.rst
git mv _sources/Unit8-2DArray/a2dSummary.rst _sources/Unit-3-Arrays/a2dSummary.rst
git mv _sources/Unit8-2DArray/Array2dParsonsPractice.rst _sources/Unit-3-Arrays/Array2dParsonsPractice.rst
git mv _sources/Unit8-2DArray/topic-8-4-toggle-problems.rst _sources/Unit-3-Arrays/topic-8-4-toggle-problems.rst
git mv _sources/Unit8-2DArray/Array2dCodePractice.rst _sources/Unit-3-Arrays/Array2dCodePractice.rst
git mv _sources/Unit8-2DArray/freeResponse.rst _sources/Unit-3-Arrays/freeResponse.rst
git mv _sources/Unit8-2DArray/grayImageA.rst _sources/Unit-3-Arrays/grayImageA.rst
git mv _sources/Unit8-2DArray/grayImageB.rst _sources/Unit-3-Arrays/grayImageB.rst
git mv _sources/Unit8-2DArray/routeCipherA.rst _sources/Unit-3-Arrays/routeCipherA.rst
git mv _sources/Unit8-2DArray/routeCipherB.rst _sources/Unit-3-Arrays/routeCipherB.rst
git mv _sources/Unit8-2DArray/Exercises.rst _sources/Unit-3-Arrays/2DArrayExercises.rst
git mv _sources/Unit8-2DArray/a2dEasyMC.rst _sources/Unit-3-Arrays/a2dEasyMC.rst
git mv _sources/Unit8-2DArray/a2dMedMC.rst _sources/Unit-3-Arrays/a2dMedMC.rst
git mv _sources/Unit8-2DArray/a2dHardMC.rst _sources/Unit-3-Arrays/a2dHardMC.rst
git mv _sources/Unit8-2DArray/CBLabs.rst _sources/Unit-3-Arrays/CBLabs.rst
git mv _sources/Unit8-2DArray/pictureLabA1toA3.rst _sources/Unit-3-Arrays/pictureLabA1toA3.rst
git mv _sources/Unit8-2DArray/pictureLabA4.rst _sources/Unit-3-Arrays/pictureLabA4.rst
git mv _sources/Unit8-2DArray/pictureLabA5.rst _sources/Unit-3-Arrays/pictureLabA5.rst
git mv _sources/Unit8-2DArray/pictureLabA6.rst _sources/Unit-3-Arrays/pictureLabA6.rst
git mv _sources/Unit8-2DArray/pictureLabA7.rst _sources/Unit-3-Arrays/pictureLabA7.rst
git mv _sources/Unit8-2DArray/pictureLabA8.rst _sources/Unit-3-Arrays/pictureLabA8.rst
git mv _sources/Unit8-2DArray/pictureLabA9.rst _sources/Unit-3-Arrays/pictureLabA9.rst
mkdir -p _sources/Unit-4-Control-constructs
git mv _sources/Unit3-If-Statements/topic-3-2-ifs.rst _sources/Unit-4-Control-constructs/topic-3-2-ifs.rst
git mv _sources/Unit3-If-Statements/topic-3-3-if-else.rst _sources/Unit-4-Control-constructs/topic-3-3-if-else.rst
git mv _sources/Unit3-If-Statements/topic-3-4-else-ifs.rst _sources/Unit-4-Control-constructs/topic-3-4-else-ifs.rst
git mv _sources/Unit3-If-Statements/topic-3-5-compound-ifs.rst _sources/Unit-4-Control-constructs/topic-3-5-compound-ifs.rst
git mv _sources/Unit3-If-Statements/topic-3-6-DeMorgan.rst _sources/Unit-4-Control-constructs/topic-3-6-DeMorgan.rst
git mv _sources/Unit3-If-Statements/topic-3-7-comparing-objects.rst _sources/Unit-4-Control-constructs/topic-3-7-comparing-objects.rst
git mv _sources/Unit3-If-Statements/topic-3-8-summary.rst _sources/Unit-4-Control-constructs/topic-3-8-summary.rst
git mv _sources/Unit3-If-Statements/topic-3-9-practice-mixed-code.rst _sources/Unit-4-Control-constructs/topic-3-9-practice-mixed-code.rst
git mv _sources/Unit3-If-Statements/topic-3-9-practice-mixed-code-toggle.rst _sources/Unit-4-Control-constructs/topic-3-9-practice-mixed-code-toggle.rst
git mv _sources/Unit3-If-Statements/topic-3-10-practice-coding.rst _sources/Unit-4-Control-constructs/topic-3-10-practice-coding.rst
git mv _sources/Unit3-If-Statements/Exercises.rst _sources/Unit-4-Control-constructs/IfExercises.rst
git mv _sources/Unit3-If-Statements/magpieindex.rst _sources/Unit-4-Control-constructs/magpieindex.rst
git mv _sources/Unit3-If-Statements/magpie1.rst _sources/Unit-4-Control-constructs/magpie1.rst
git mv _sources/Unit3-If-Statements/magpie2.rst _sources/Unit-4-Control-constructs/magpie2.rst
git mv _sources/Unit3-If-Statements/magpie3.rst _sources/Unit-4-Control-constructs/magpie3.rst
git mv _sources/Unit3-If-Statements/magpie4.rst _sources/Unit-4-Control-constructs/magpie4.rst
git mv _sources/Unit3-If-Statements/magpie-exercises.rst _sources/Unit-4-Control-constructs/magpie-exercises.rst
git mv _sources/Unit4-Iteration/topic-4-1-while-loops.rst _sources/Unit-4-Control-constructs/topic-4-1-while-loops.rst
git mv _sources/Unit4-Iteration/topic-4-2-for-loops.rst _sources/Unit-4-Control-constructs/topic-4-2-for-loops.rst
git mv _sources/Unit4-Iteration/topic-4-3-strings-loops.rst _sources/Unit-4-Control-constructs/topic-4-3-strings-loops.rst
git mv _sources/Unit4-Iteration/topic-4-4-nested-loops.rst _sources/Unit-4-Control-constructs/topic-4-4-nested-loops.rst
git mv _sources/Unit4-Iteration/topic-4-5-loop-analysis.rst _sources/Unit-4-Control-constructs/topic-4-5-loop-analysis.rst
git mv _sources/Unit4-Iteration/topic-4-6-summary.rst _sources/Unit-4-Control-constructs/topic-4-6-summary.rst
git mv _sources/Unit4-Iteration/topic-4-6-group-mod.rst _sources/Unit-4-Control-constructs/topic-4-6-group-mod.rst
git mv _sources/Unit4-Iteration/topic-4-7-practice-mixed-code.rst _sources/Unit-4-Control-constructs/topic-4-7-practice-mixed-code.rst
git mv _sources/Unit4-Iteration/topic-4-7-practice-mixed-code-toggle.rst _sources/Unit-4-Control-constructs/topic-4-7-practice-mixed-code-toggle.rst
git mv _sources/Unit4-Iteration/topic-4-8-practice-coding.rst _sources/Unit-4-Control-constructs/topic-4-8-practice-coding.rst
git mv _sources/Unit4-Iteration/Exercises.rst _sources/Unit-4-Control-constructs/LoopExercises.rst
git mv _sources/Unit4-Iteration/FRQcalendar.rst _sources/Unit-4-Control-constructs/FRQcalendar.rst
git mv _sources/Unit4-Iteration/FRQselfDivisorA.rst _sources/Unit-4-Control-constructs/FRQselfDivisorA.rst
git mv _sources/Unit4-Iteration/FRQstringScrambleA.rst _sources/Unit-4-Control-constructs/FRQstringScrambleA.rst
git mv _sources/Unit4-Iteration/ConsumerReviewLab.rst _sources/Unit-4-Control-constructs/ConsumerReviewLab.rst
mkdir -p _sources/Unit-5-Methods
git mv _sources/Unit-Sqrt2-Methods/topic-sqrt2-1-using-methods.rst _sources/Unit-5-Methods/topic-sqrt2-1-using-methods.rst
git mv _sources/Unit-Sqrt2-Methods/topic-sqrt2-2-writing-methods.rst _sources/Unit-5-Methods/topic-sqrt2-2-writing-methods.rst
git mv _sources/Unit2-Using-Objects/topic-2-1-objects-intro-turtles.rst _sources/Unit-5-Methods/topic-2-1-objects-intro-turtles.rst
git mv _sources/Unit2-Using-Objects/topic-2-2-constructors.rst _sources/Unit-5-Methods/topic-2-2-constructors.rst
git mv _sources/Unit2-Using-Objects/topic-2-3-methods-no-params.rst _sources/Unit-5-Methods/topic-2-3-methods-no-params.rst
git mv _sources/Unit2-Using-Objects/topic-2-4-methods-with-params.rst _sources/Unit-5-Methods/topic-2-4-methods-with-params.rst
git mv _sources/Unit2-Using-Objects/topic-2-5-methods-return.rst _sources/Unit-5-Methods/topic-2-5-methods-return.rst
git mv _sources/Unit2-Using-Objects/topic-2-10-summary.rst _sources/Unit-5-Methods/topic-2-10-summary.rst
git mv _sources/Unit2-Using-Objects/topic-2-11-practice-mixed-code.rst _sources/Unit-5-Methods/topic-2-11-practice-mixed-code.rst
git mv _sources/Unit2-Using-Objects/topic-2-11-practice-mixed-code-toggle.rst _sources/Unit-5-Methods/topic-2-11-practice-mixed-code-toggle.rst
git mv _sources/Unit2-Using-Objects/topic-2-12-practice-coding.rst _sources/Unit-5-Methods/topic-2-12-practice-coding.rst
git mv _sources/Unit2-Using-Objects/practice-test-objects.rst _sources/Unit-5-Methods/practice-test-objects.rst
git mv _sources/Unit2-Using-Objects/Exercises.rst _sources/Unit-5-Methods/Exercises.rst
git mv _sources/Unit2-Using-Objects/JavaSwingGUIs.rst _sources/Unit-5-Methods/JavaSwingGUIs.rst
mkdir -p _sources/Unit-6-Writing-Classes
git mv _sources/Unit5-Writing-Classes/topic-5-1-parts-of-class.rst _sources/Unit-6-Writing-Classes/topic-5-1-parts-of-class.rst
git mv _sources/Unit5-Writing-Classes/topic-5-2-writing-constructors.rst _sources/Unit-6-Writing-Classes/topic-5-2-writing-constructors.rst
git mv _sources/Unit5-Writing-Classes/topic-5-3-comments-conditions.rst _sources/Unit-6-Writing-Classes/topic-5-3-comments-conditions.rst
git mv _sources/Unit5-Writing-Classes/topic-5-4-accessor-methods.rst _sources/Unit-6-Writing-Classes/topic-5-4-accessor-methods.rst
git mv _sources/Unit5-Writing-Classes/topic-5-5-mutator-methods.rst _sources/Unit-6-Writing-Classes/topic-5-5-mutator-methods.rst
git mv _sources/Unit5-Writing-Classes/topic-5-6-writing-methods.rst _sources/Unit-6-Writing-Classes/topic-5-6-writing-methods.rst
git mv _sources/Unit5-Writing-Classes/topic-5-7-static-vars-methods.rst _sources/Unit-6-Writing-Classes/topic-5-7-static-vars-methods.rst
git mv _sources/Unit5-Writing-Classes/topic-5-8-scope-access.rst _sources/Unit-6-Writing-Classes/topic-5-8-scope-access.rst
git mv _sources/Unit5-Writing-Classes/topic-5-10-social-impacts.rst _sources/Unit-6-Writing-Classes/topic-5-10-social-impacts.rst
git mv _sources/Unit5-Writing-Classes/topic-5-11-summary.rst _sources/Unit-6-Writing-Classes/topic-5-11-summary.rst
git mv _sources/Unit5-Writing-Classes/topic-parsons-practice.rst _sources/Unit-6-Writing-Classes/topic-parsons-practice.rst
git mv _sources/Unit5-Writing-Classes/topic-toggle-problems.rst _sources/Unit-6-Writing-Classes/topic-toggle-problems.rst
git mv _sources/Unit5-Writing-Classes/Exercises.rst _sources/Unit-6-Writing-Classes/Exercises.rst
git mv _sources/Unit5-Writing-Classes/midterm_unit5.rst _sources/Unit-6-Writing-Classes/midterm_unit5.rst
git mv _sources/Unit5-Writing-Classes/FRQstepTracker.rst _sources/Unit-6-Writing-Classes/FRQstepTracker.rst
git mv _sources/Unit5-Writing-Classes/timeFRQ.rst _sources/Unit-6-Writing-Classes/timeFRQ.rst
git mv _sources/Unit5-Writing-Classes/APLine.rst _sources/Unit-6-Writing-Classes/APLine.rst
git mv _sources/Unit5-Writing-Classes/CBLabs.rst _sources/Unit-6-Writing-Classes/CBLabs.rst
git mv _sources/Unit5-Writing-Classes/community-challenge.rst _sources/Unit-6-Writing-Classes/community-challenge.rst
mkdir -p _sources/Unit-7-Built-in-classes
git mv _sources/Unit2-Using-Objects/topic-2-6-strings.rst _sources/Unit-7-Built-in-classes/topic-2-6-strings.rst
git mv _sources/Unit2-Using-Objects/topic-2-7-string-methods.rst _sources/Unit-7-Built-in-classes/topic-2-7-string-methods.rst
git mv _sources/Unit2-Using-Objects/topic-2-8-IntegerDouble.rst _sources/Unit-7-Built-in-classes/topic-2-8-IntegerDouble.rst
git mv _sources/Unit2-Using-Objects/topic-2-9-Math.rst _sources/Unit-7-Built-in-classes/topic-2-9-Math.rst
git mv _sources/Unit7-ArrayList/topic-7-1-arraylist-basics.rst _sources/Unit-7-Built-in-classes/topic-7-1-arraylist-basics.rst
git mv _sources/Unit7-ArrayList/topic-7-2-arraylist-methods.rst _sources/Unit-7-Built-in-classes/topic-7-2-arraylist-methods.rst
git mv _sources/Unit7-ArrayList/topic-7-3-arraylist-loops.rst _sources/Unit-7-Built-in-classes/topic-7-3-arraylist-loops.rst
git mv _sources/Unit7-ArrayList/topic-7-4-arraylist-algorithms.rst _sources/Unit-7-Built-in-classes/topic-7-4-arraylist-algorithms.rst
git mv _sources/Unit7-ArrayList/stringScrambleB.rst _sources/Unit-7-Built-in-classes/stringScrambleB.rst
git mv _sources/Unit7-ArrayList/climbClubA.rst _sources/Unit-7-Built-in-classes/climbClubA.rst
git mv _sources/Unit7-ArrayList/climbClubB.rst _sources/Unit-7-Built-in-classes/climbClubB.rst
git mv _sources/Unit7-ArrayList/climbClubC.rst _sources/Unit-7-Built-in-classes/climbClubC.rst
git mv _sources/Unit7-ArrayList/cookieOrderA.rst _sources/Unit-7-Built-in-classes/cookieOrderA.rst
git mv _sources/Unit7-ArrayList/cookieOrderB.rst _sources/Unit-7-Built-in-classes/cookieOrderB.rst
git mv _sources/Unit7-ArrayList/2016freeresponseQ4A.rst _sources/Unit-7-Built-in-classes/2016freeresponseQ4A.rst
git mv _sources/Unit7-ArrayList/2016freeresponseQ4B.rst _sources/Unit-7-Built-in-classes/2016freeresponseQ4B.rst
git mv _sources/Unit7-ArrayList/2019delimitersQ3a.rst _sources/Unit-7-Built-in-classes/2019delimitersQ3a.rst
git mv _sources/Unit7-ArrayList/2019delimitersQ3b.rst _sources/Unit-7-Built-in-classes/2019delimitersQ3b.rst
git mv _sources/Unit7-ArrayList/2013gridworldQ3A.rst _sources/Unit-7-Built-in-classes/2013gridworldQ3A.rst
git mv _sources/Unit7-ArrayList/topic-7-5-searching.rst _sources/Unit-7-Built-in-classes/topic-7-5-searching.rst
git mv _sources/Unit7-ArrayList/topic-7-6-sorting.rst _sources/Unit-7-Built-in-classes/topic-7-6-sorting.rst
git mv _sources/Unit7-ArrayList/topic-7-7-data-ethics.rst _sources/Unit-7-Built-in-classes/topic-7-7-data-ethics.rst
git mv _sources/Unit7-ArrayList/topic-7-8-summary.rst _sources/Unit-7-Built-in-classes/topic-7-8-summary.rst
git mv _sources/Unit7-ArrayList/topic-input-files.rst _sources/Unit-7-Built-in-classes/topic-input-files.rst
git mv _sources/Unit7-ArrayList/ListParsonsPractice.rst _sources/Unit-7-Built-in-classes/ListParsonsPractice.rst
git mv _sources/Unit7-ArrayList/topic-7-9-toggle-problems.rst _sources/Unit-7-Built-in-classes/topic-7-9-toggle-problems.rst
git mv _sources/Unit7-ArrayList/listPractice.rst _sources/Unit-7-Built-in-classes/listPractice.rst
git mv _sources/Unit7-ArrayList/Exercises.rst _sources/Unit-7-Built-in-classes/Exercises.rst
git mv _sources/Unit7-ArrayList/listEasyMC.rst _sources/Unit-7-Built-in-classes/listEasyMC.rst
git mv _sources/Unit7-ArrayList/listMedMC.rst _sources/Unit-7-Built-in-classes/listMedMC.rst
git mv _sources/Unit7-ArrayList/listHardMC.rst _sources/Unit-7-Built-in-classes/listHardMC.rst
git mv _sources/Unit7-ArrayList/ssEasyMC.rst _sources/Unit-7-Built-in-classes/ssEasyMC.rst
git mv _sources/Unit7-ArrayList/ssMedMC.rst _sources/Unit-7-Built-in-classes/ssMedMC.rst
git mv _sources/Unit7-ArrayList/ssHardMC.rst _sources/Unit-7-Built-in-classes/ssHardMC.rst
git mv _sources/Unit7-ArrayList/CBLabs.rst _sources/Unit-7-Built-in-classes/CBLabs.rst
mkdir -p _sources/Unit-8-Inheritance
git mv _sources/Unit9-Inheritance/topic-9-1-inheritance.rst _sources/Unit-8-Inheritance/topic-9-1-inheritance.rst
git mv _sources/Unit9-Inheritance/topic-9-1-inheritance-day1.rst _sources/Unit-8-Inheritance/topic-9-1-inheritance-day1.rst
git mv _sources/Unit9-Inheritance/topic-9-1-inheritance-day2.rst _sources/Unit-8-Inheritance/topic-9-1-inheritance-day2.rst
git mv _sources/Unit9-Inheritance/topic-9-2-constructors.rst _sources/Unit-8-Inheritance/topic-9-2-constructors.rst
git mv _sources/Unit9-Inheritance/topic-9-3-overriding.rst _sources/Unit-8-Inheritance/topic-9-3-overriding.rst
git mv _sources/Unit9-Inheritance/topic-9-4-super.rst _sources/Unit-8-Inheritance/topic-9-4-super.rst
git mv _sources/Unit9-Inheritance/topic-9-5-hierarchies.rst _sources/Unit-8-Inheritance/topic-9-5-hierarchies.rst
git mv _sources/Unit9-Inheritance/topic-9-6-polymorphism.rst _sources/Unit-8-Inheritance/topic-9-6-polymorphism.rst
git mv _sources/Unit9-Inheritance/topic-9-7-Object.rst _sources/Unit-8-Inheritance/topic-9-7-Object.rst
git mv _sources/Unit9-Inheritance/ooSummary.rst _sources/Unit-8-Inheritance/ooSummary.rst
git mv _sources/Unit9-Inheritance/freeResponse.rst _sources/Unit-8-Inheritance/freeResponse.rst
git mv _sources/Unit9-Inheritance/TrioA.rst _sources/Unit-8-Inheritance/TrioA.rst
git mv _sources/Unit9-Inheritance/TrioScore1.rst _sources/Unit-8-Inheritance/TrioScore1.rst
git mv _sources/Unit9-Inheritance/TrioScore2.rst _sources/Unit-8-Inheritance/TrioScore2.rst
git mv _sources/Unit9-Inheritance/TrioScore3.rst _sources/Unit-8-Inheritance/TrioScore3.rst
git mv _sources/Unit9-Inheritance/ooParsonsPractice.rst _sources/Unit-8-Inheritance/ooParsonsPractice.rst
git mv _sources/Unit9-Inheritance/topic-9-10-toggle-problems.rst _sources/Unit-8-Inheritance/topic-9-10-toggle-problems.rst
git mv _sources/Unit9-Inheritance/ooCodePractice.rst _sources/Unit-8-Inheritance/ooCodePractice.rst
git mv _sources/Unit9-Inheritance/Exercises.rst _sources/Unit-8-Inheritance/Exercises.rst
git mv _sources/Unit9-Inheritance/ooEasyMC.rst _sources/Unit-8-Inheritance/ooEasyMC.rst
git mv _sources/Unit9-Inheritance/ooMedMC.rst _sources/Unit-8-Inheritance/ooMedMC.rst
git mv _sources/Unit9-Inheritance/ooHardMC.rst _sources/Unit-8-Inheritance/ooHardMC.rst
git mv _sources/Unit9-Inheritance/ooPractice.rst _sources/Unit-8-Inheritance/ooPractice.rst
git mv _sources/Unit9-Inheritance/CBLabs.rst _sources/Unit-8-Inheritance/CBLabs.rst
mkdir -p _sources/Unit-9-OO-design
mkdir -p _sources/Unit-10-Algorithms
git mv _sources/Unit10-Recursion/topic-10-1-recursion.rst _sources/Unit-10-Algorithms/topic-10-1-recursion.rst
git mv _sources/Unit10-Recursion/topic-10-1-recursion-day1.rst _sources/Unit-10-Algorithms/topic-10-1-recursion-day1.rst
git mv _sources/Unit10-Recursion/topic-10-1-recursion-day2.rst _sources/Unit-10-Algorithms/topic-10-1-recursion-day2.rst
git mv _sources/Unit10-Recursion/topic-10-1-recursion-challenge.rst _sources/Unit-10-Algorithms/topic-10-1-recursion-challenge.rst
git mv _sources/Unit10-Recursion/topic-10-2-recursive-search-sort.rst _sources/Unit-10-Algorithms/topic-10-2-recursive-search-sort.rst
git mv _sources/Unit10-Recursion/summary.rst _sources/Unit-10-Algorithms/summary.rst
git mv _sources/Unit10-Recursion/rParsonsPractice.rst _sources/Unit-10-Algorithms/rParsonsPractice.rst
git mv _sources/Unit10-Recursion/rMixedUpCodePractice.rst _sources/Unit-10-Algorithms/rMixedUpCodePractice.rst
git mv _sources/Unit10-Recursion/topic-10-4-toggle-problems.rst _sources/Unit-10-Algorithms/topic-10-4-toggle-problems.rst
git mv _sources/Unit10-Recursion/recursionCodePractice.rst _sources/Unit-10-Algorithms/recursionCodePractice.rst
git mv _sources/Unit10-Recursion/Exercises.rst _sources/Unit-10-Algorithms/Exercises.rst
git mv _sources/Unit10-Recursion/rBasePractice.rst _sources/Unit-10-Algorithms/rBasePractice.rst
git mv _sources/Unit10-Recursion/rEasyMC.rst _sources/Unit-10-Algorithms/rEasyMC.rst
git mv _sources/Unit10-Recursion/rMedMC.rst _sources/Unit-10-Algorithms/rMedMC.rst
git mv _sources/Unit10-Recursion/rHardMC.rst _sources/Unit-10-Algorithms/rHardMC.rst
mkdir -p _sources/Unit-11-posttest
git mv _sources/Unit11-posttest/posttest.rst _sources/Unit-11-posttest/posttest.rst
mkdir -p _sources/Tests
# testPractice.rst doesn't move
# test1nt.rst doesn't move
# test2nt.rst doesn't move
# test3nt.rst doesn't move
# test4nt.rst doesn't move
# test5nt.rst doesn't move
# Exercises.rst doesn't move
mkdir -p _sources/TimedTests
# test1.rst doesn't move
# test3.rst doesn't move
# test4.rst doesn't move
# Exercises.rst doesn't move
# apbowla.rst doesn't move
mkdir -p _sources/MixedFreeResponse
# RandomStringChooserParsonsA.rst doesn't move
# RandomStringChooserA2.rst doesn't move
# RandomStringChooserParsonsB.rst doesn't move
# RandomStringChooserB2.rst doesn't move
# Exercises.rst doesn't move
mkdir -p _sources/FreeResponse
# RandomStringChooserA.rst doesn't move
# RandomStringChooserB.rst doesn't move
# StringCoderA.rst doesn't move
# StringCoderB.rst doesn't move
# StudentAnswerSheetA.rst doesn't move
# StudentAnswerSheetB.rst doesn't move
# SkyViewA.rst doesn't move
# SkyViewB.rst doesn't move
# HiddenWord.rst doesn't move
# ArrayTesterA.rst doesn't move
# ArrayTesterB.rst doesn't move
# NumberGroupB.rst doesn't move
# NumberGroupC.rst doesn't move
# Exercises.rst doesn't move
mkdir -p _sources/Stories
# challengesInComputing.rst doesn't move
# intervieweeIndex.rst doesn't move
# Interviewees/A_Taylor.rst doesn't move
# Interviewees/B_Hickerson.rst doesn't move
# Interviewees/B_Mariscal.rst doesn't move
# Interviewees/C_De_Lira.rst doesn't move
# Interviewees/C_Mbayo.rst doesn't move
# Interviewees/D_Deinde-Smith.rst doesn't move
# Interviewees/E_Espinoza.rst doesn't move
# Interviewees/G_Opoku-Boateng.rst doesn't move
# Interviewees/J_Gilbert.rst doesn't move
# Interviewees/L_Morales.rst doesn't move
# Interviewees/L_Vocos.rst doesn't move
# Interviewees/L_Diaz.rst doesn't move
# Interviewees/M_Rodriguez.rst doesn't move
# Interviewees/N_Gaskins.rst doesn't move
mkdir -p _sources/_hidden
# Ex-array-orig.rst doesn't move
