#!/usr/bin/env bash

set -euo pipefail

trap cleanup INT

cleanup() {
    watchman trigger-del pretext rebuild
}

if [[ "$(watchman watch-list pretext | jq .roots)" == "[]" ]]; then
    watchman watch pretext
fi

log="$(dirname $(watchman get-sockname | jq -r '.sockname'))/log"

watchman -j <<EOF
["trigger", "$(pwd)/pretext", {
  "name": "rebuild",
  "append_files": false,
  "command": [ "uv", "run", "pretext", "view", "web", "-b", "--no-launch" ]
}]
EOF

tail -f "$log"
